# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y
# Improved antenna power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y
